# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Clean images

on: 
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 1 * *"  # every day at midnight

jobs:
  clean-ghcr:
      name: Delete old unused container images
      runs-on: ubuntu-latest
      steps:
        - name: delete containers
          uses: snok/container-retention-policy@v1.5.1
          with:
            image-names: raganhar/ghcr-ecr-deploy-push*
            cut-off: 19 days ago UTC
            account-type: personal
            keep-at-least: 4
            token: ${{ secrets.MY_PAT }}